import { readFile, stat, writeFile } from "node:fs/promises";
import { dirname, extname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const audioDir = join(root, "assets", "audio");
const output = join(root, "src", "generated", "audio.generated.ts");
const extensions = [".mp3", ".ogg", ".wav", ".m4a", ".aac"];
const slots = [
  ["inferno", "Inferno"],
  ["bling-bang-bang-born", "Bling-Bang-Bang-Born"],
  ["otonoke", "Otonoke"],
  ["black-catcher", "Black Catcher"]
];
const mime = { ".mp3": "audio/mpeg", ".ogg": "audio/ogg", ".wav": "audio/wav", ".m4a": "audio/mp4", ".aac": "audio/aac" };

const embedded = {};
for (const [base, label] of slots) {
  for (const extension of extensions) {
    const path = join(audioDir, base + extension);
    try {
      const info = await stat(path);
      if (!info.isFile()) continue;
      const bytes = await readFile(path);
      embedded[label] = `data:${mime[extname(path)]};base64,${bytes.toString("base64")}`;
      break;
    } catch {}
  }
}

const source = `// Generated by scripts/generate-audio.mjs. Do not edit.\n` +
`export function createAudioRegistry() {\n  return ${JSON.stringify(embedded)} as Record<string, string>;\n}\n`;
await writeFile(output, source, "utf8");
console.log(`Embedded ${Object.keys(embedded).length} private soundtrack file(s).`);
