import type { WrappedSession, WrappedSettings } from "./domain";

export interface ViewerInput {
  session: WrappedSession;
  settings: WrappedSettings;
}

export function createViewer() {
  function completedSlideDuration(count: number): number {
    const shown = Math.min(6, Math.max(0, Math.floor(count)));
    return shown <= 1 ? 6000 : shown * 3000;
  }

  function safeJson(value: unknown): string {
    return JSON.stringify(value).replace(/</g, "\\u003c").replace(/>/g, "\\u003e").replace(/&/g, "\\u0026");
  }

  function documentFor(input: ViewerInput): string {
    const payload = safeJson({
      ...input,
      completedDuration: completedSlideDuration(input.session.completed.length),
      periodHeadline: input.session.period.label.replace(/\s+\d{4}$/, "").replace(/^Your\s+/, ""),
      scoreLabels: {
        highestRated: input.session.highestRated?.userScore === null || input.session.highestRated?.userScore === undefined
          ? null
          : Number(input.session.highestRated.userScore).toFixed(1),
        average: input.session.averageScore === null ? null : Number(input.session.averageScore).toFixed(1)
      }
    });
    return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>Seanime Wrapped</title>
<style>
:root{color-scheme:dark;--pink:#f14fd9;--violet:#8b5cf6;--blue:#5d79ff;--glass:rgba(10,14,29,.55);--line:rgba(255,255,255,.17);--ease:cubic-bezier(.22,.8,.2,1)}
*{box-sizing:border-box}html,body{width:100%;height:100%;margin:0;overflow:hidden;background:#060914;color:#fff;font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif}button{font:inherit;color:inherit}
#app{position:fixed;inset:0;isolation:isolate;background:#070a14;opacity:1;transition:opacity .32s ease}.closing{opacity:0!important}
.background,.bg-layer,.veil,.grain{position:absolute;inset:-4%}.bg-layer{background:center/cover no-repeat;filter:blur(16px) saturate(1.22);transform:scale(1.08);opacity:0;transition:opacity 1s ease,transform 8s var(--ease)}.bg-layer.active{opacity:.68;transform:scale(1.13)}
.veil{inset:0;background:radial-gradient(circle at 78% 30%,transparent 0,rgba(3,6,18,.18) 32%,rgba(3,6,18,.82) 78%),linear-gradient(90deg,rgba(4,7,18,.94),rgba(4,7,18,.45) 58%,rgba(4,7,18,.78));z-index:1}.grain{z-index:2;opacity:.08;pointer-events:none;background-image:url("data:image/svg+xml,%3Csvg viewBox='0 0 180 180' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='.8' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='.7'/%3E%3C/svg%3E")}
.chrome{position:absolute;z-index:20;top:0;left:0;right:0;padding:max(18px,2.3vh) clamp(22px,4vw,74px);display:grid;gap:15px}.progress{display:flex;gap:7px}.segment{height:4px;flex:1;border-radius:99px;background:rgba(255,255,255,.23);overflow:hidden}.segment>i{display:block;width:0;height:100%;background:#fff;box-shadow:0 0 12px rgba(255,255,255,.65)}
.topline{display:flex;align-items:center;justify-content:space-between}.brand{display:flex;align-items:center;gap:12px;font-weight:760;letter-spacing:-.02em}.logo{display:flex;align-items:end;gap:3px;height:27px}.logo i{display:block;width:6px;border-radius:7px;background:linear-gradient(180deg,#ff99a8,#e84fe0 55%,#596dff)}.logo i:nth-child(1){height:12px}.logo i:nth-child(2){height:21px}.logo i:nth-child(3){height:27px}.logo i:nth-child(4){height:17px}.actions{display:flex;gap:9px}.icon-btn{width:42px;height:42px;border:1px solid rgba(255,255,255,.13);border-radius:50%;background:rgba(5,8,20,.52);backdrop-filter:blur(14px);display:grid;place-items:center;cursor:pointer;transition:transform .2s ease,background .2s}.icon-btn svg{width:20px;height:20px;fill:none;stroke:currentColor;stroke-width:2;stroke-linecap:round;stroke-linejoin:round}.icon-btn .filled{fill:currentColor;stroke:none}.icon-btn:hover{background:rgba(255,255,255,.13);transform:scale(1.05)}.icon-btn:focus-visible{outline:3px solid #fff;outline-offset:3px}
.stage{position:absolute;inset:0;z-index:5}.slide{position:absolute;inset:0;padding:clamp(100px,14vh,145px) clamp(34px,8vw,140px) clamp(38px,7vh,75px);display:none;opacity:0;transform:scale(1.025);transition:opacity .55s ease,transform .7s var(--ease)}.slide.active{display:flex;opacity:1;transform:scale(1)}
.slide-inner{width:min(1420px,100%);height:100%;margin:auto;display:flex;align-items:center;position:relative}.eyebrow{font-size:clamp(12px,1vw,16px);text-transform:uppercase;letter-spacing:.16em;color:#d8d9ff;font-weight:750}.display{padding-bottom:.12em;overflow:visible;font-size:clamp(58px,8.4vw,138px);line-height:1.02;letter-spacing:-.065em;margin:14px 0 24px;max-width:920px}.gradient{display:inline-block;line-height:1.1;padding:.05em .03em .12em 0;overflow:visible;background:linear-gradient(110deg,#fff 8%,#efc8ff 35%,#ec52d7 70%,#7c8fff);-webkit-background-clip:text;background-clip:text;color:transparent}.subtitle{font-size:clamp(17px,1.6vw,27px);line-height:1.45;color:rgba(255,255,255,.78);max-width:620px}.reveal>*{opacity:0;transform:translateY(28px);filter:blur(8px)}.active .reveal>*{animation:reveal .72s var(--ease) forwards}.active .reveal>*:nth-child(2){animation-delay:.1s}.active .reveal>*:nth-child(3){animation-delay:.2s}.active .reveal>*:nth-child(4){animation-delay:.3s}@keyframes reveal{to{opacity:1;transform:none;filter:none}}
.count-layout{justify-content:space-between;gap:6vw;overflow:visible}.count-copy{max-width:620px;overflow:visible}.mega{font-size:clamp(84px,15vw,230px);line-height:.92;font-weight:900;letter-spacing:-.065em;padding:.05em .08em .12em .02em;overflow:visible;text-shadow:0 0 50px rgba(235,70,215,.3)}.posters{position:relative;width:min(42vw,610px);height:min(64vh,620px)}.poster{position:absolute;left:50%;top:50%;width:clamp(130px,15vw,220px);aspect-ratio:2/3;object-fit:cover;border-radius:18px;border:1px solid rgba(255,255,255,.3);box-shadow:0 30px 80px rgba(0,0,0,.55);transform:translate(-50%,-50%) rotate(var(--r)) translateX(var(--x));transition:transform 1s var(--ease);animation:posterIn .9s var(--ease) both;animation-delay:var(--d)}@keyframes posterIn{from{opacity:0;transform:translate(-50%,-40%) rotate(0) scale(.65)}}.shuffle-deck{position:relative;width:min(49vw,700px);height:min(60vh,580px);overflow:visible}.shuffle-poster{position:absolute;top:50%;left:50%;width:clamp(115px,13vw,190px);aspect-ratio:2/3;object-fit:cover;border-radius:18px;border:1px solid rgba(255,255,255,.32);box-shadow:0 24px 70px rgba(0,0,0,.55);transform:translate(-50%,-50%);transition:left 1s var(--ease),transform 1s var(--ease),filter 1s var(--ease);will-change:left,transform}
.genre-layout{display:grid;grid-template-columns:minmax(300px,.8fr) minmax(400px,1.2fr);gap:9vw;align-items:center}.genre-name{font-size:clamp(64px,9vw,150px);font-weight:900;letter-spacing:-.06em;line-height:1}.donut{width:min(24vw,310px);aspect-ratio:1;border-radius:50%;display:grid;place-items:center;margin-top:30px;background:conic-gradient(var(--pink) calc(var(--p)*1%),rgba(255,255,255,.13) 0);box-shadow:0 0 55px rgba(230,65,214,.25)}.donut:after{content:attr(data-label);width:67%;aspect-ratio:1;border-radius:50%;background:rgba(7,10,22,.9);display:grid;place-items:center;font-size:clamp(30px,4vw,60px);font-weight:850}.bars{display:grid;gap:18px}.bar-row{display:grid;grid-template-columns:130px 1fr 48px;gap:18px;align-items:center}.bar-track{height:12px;background:rgba(255,255,255,.1);border-radius:99px;overflow:hidden}.bar-fill{height:100%;width:0;border-radius:inherit;background:linear-gradient(90deg,var(--blue),var(--pink));transition:width 1.2s var(--ease) .25s}.active .bar-fill{width:var(--w)}
.rank-layout{display:grid;grid-template-columns:minmax(300px,.9fr) minmax(420px,1.1fr);gap:7vw}.rank-poster{justify-self:end;width:min(31vw,440px);max-height:66vh;aspect-ratio:2/3;object-fit:cover;border-radius:26px;border:1px solid rgba(255,255,255,.25);box-shadow:0 40px 100px rgba(0,0,0,.6),0 0 70px color-mix(in srgb,var(--accent) 35%,transparent);animation:rankPoster 1s var(--ease) both}@keyframes rankPoster{from{opacity:0;transform:translateX(-60px) rotate(-5deg) scale(.88)}}.rank-number{font-size:clamp(82px,13vw,220px);font-weight:950;letter-spacing:-.08em;line-height:1;color:var(--accent)}.rank-title{font-size:clamp(38px,5vw,78px);line-height:1;letter-spacing:-.045em;margin:26px 0 18px}.winner .rank-poster{width:min(32vw,455px);border:2px solid #FFD76A;box-shadow:0 40px 110px rgba(0,0,0,.65),0 0 65px rgba(255,215,106,.28)}.winner .rank-number{color:#FFD76A;text-shadow:0 0 32px rgba(255,215,106,.2)}
.overview{align-items:flex-end}.overview-grid{width:100%;display:grid;grid-template-columns:repeat(5,1fr);align-items:end;gap:14px}.overview-card{position:relative;min-width:0;border-radius:18px;overflow:hidden;border:1px solid rgba(255,255,255,.18);background:var(--glass);box-shadow:0 20px 60px rgba(0,0,0,.35);animation:cardUp .7s var(--ease) both;animation-delay:var(--d)}.overview-card.winner-card{translate:0 -16px;scale:1.025;border:2px solid #FFD76A;box-shadow:0 20px 60px rgba(0,0,0,.35),0 0 32px rgba(255,215,106,.22)}.winner-card .card-rank{color:#FFD76A}@keyframes cardUp{from{opacity:0;transform:translateY(60px)}}.overview-card img{display:block;width:100%;aspect-ratio:2/3;object-fit:cover}.card-copy{padding:14px}.card-rank{position:absolute;top:12px;left:12px;font-size:30px;font-weight:900;text-shadow:0 3px 12px #000}.card-title{font-weight:750;white-space:nowrap;text-overflow:ellipsis;overflow:hidden}.meta{font-size:13px;color:rgba(255,255,255,.62);margin-top:5px}
.spotlight{display:grid;grid-template-columns:minmax(300px,1fr) minmax(310px,.9fr);gap:7vw}.spotlight-copy{align-self:center}.spotlight-title{font-size:clamp(46px,6.2vw,102px);line-height:1;letter-spacing:-.055em;margin:15px 0}.hero-card{position:relative;justify-self:end;width:min(34vw,470px);height:min(66vh,650px);border-radius:28px;overflow:hidden;border:1px solid rgba(255,255,255,.22);box-shadow:0 40px 100px rgba(0,0,0,.58)}.hero-card img{width:100%;height:100%;object-fit:cover}.hero-card:after{content:"";position:absolute;inset:45% 0 0;background:linear-gradient(transparent,rgba(5,7,16,.96))}.hero-details{position:absolute;z-index:2;left:28px;right:28px;bottom:26px}.score{font-size:clamp(62px,8vw,120px);font-weight:930;letter-spacing:-.07em}.score small{font-size:.25em;color:rgba(255,255,255,.7);letter-spacing:0}
.studio-wall{position:absolute;right:0;width:55%;height:74%;display:grid;grid-template-columns:repeat(4,1fr);gap:12px;opacity:.78;mask-image:linear-gradient(90deg,transparent,#000 25%)}.studio-wall img{width:100%;height:100%;min-height:0;object-fit:cover;border-radius:16px}.studio-name{position:relative;z-index:2;font-size:clamp(70px,11vw,180px);font-weight:930;letter-spacing:-.07em;line-height:1;max-width:850px}.compact-posters{display:flex;gap:10px;margin-top:28px}.compact-posters img{width:80px;aspect-ratio:2/3;object-fit:cover;border-radius:10px;border:1px solid rgba(255,255,255,.25)}
.recommend{align-items:flex-start}.recommend-head{display:flex;justify-content:space-between;align-items:end;margin:0 auto 18px;width:min(1120px,100%)}.recommend-head h2{font-size:clamp(32px,3.7vw,58px);margin:0;letter-spacing:-.045em}.rec-grid{display:grid;grid-template-columns:repeat(5,minmax(120px,180px));justify-content:center;gap:18px 22px;margin:auto}.rec-card{aspect-ratio:2/3;min-width:0;padding:0;color:inherit;text-align:left;font:inherit;position:relative;overflow:hidden;border:1px solid rgba(255,255,255,.16);border-radius:15px;background:rgba(9,13,27,.7);cursor:pointer;animation:cardUp .6s var(--ease) both;animation-delay:calc(var(--i)*55ms)}.rec-card:focus-visible{outline:3px solid #fff;outline-offset:3px}.rec-card img{width:100%;height:100%;object-fit:cover}.rec-card:after{content:"";position:absolute;inset:38% 0 0;background:linear-gradient(transparent,rgba(5,8,18,.98) 70%)}.rec-copy{position:absolute;z-index:2;left:12px;right:12px;bottom:10px}.rec-copy b{font-size:13px;line-height:1.18;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden;min-height:2.36em}.rec-rating{display:block;color:#ffd86b;font-size:12px;font-weight:800;margin-top:5px}.rec-rank{position:absolute;z-index:3;top:9px;left:10px;width:28px;height:28px;border-radius:8px;background:rgba(6,8,18,.78);display:grid;place-items:center;font-weight:850}.reason{display:inline-block;font-size:9px;padding:3px 6px;border-radius:99px;background:rgba(126,94,255,.58);margin-top:5px;white-space:nowrap;max-width:100%;overflow:hidden;text-overflow:ellipsis}
.final{align-items:center;justify-content:center;text-align:center}.final h1{font-size:clamp(50px,7vw,110px);line-height:1;letter-spacing:-.06em;margin:12px 0 35px}.summary{display:grid;grid-template-columns:repeat(2,minmax(260px,1fr));gap:10px;width:min(850px,90vw);text-align:left}.summary div{padding:16px 20px;border:1px solid var(--line);border-radius:14px;background:rgba(9,12,26,.45);backdrop-filter:blur(12px)}.thanks{margin-top:34px;font-size:clamp(18px,2vw,28px);color:#f0cbff}
.nav-hint{position:absolute;z-index:15;bottom:22px;left:50%;transform:translateX(-50%);font-size:12px;color:rgba(255,255,255,.45);pointer-events:none}.loading{position:absolute;inset:0;z-index:30;display:grid;place-items:center;background:#080b17;transition:opacity .45s}.loading.hidden{opacity:0;pointer-events:none}.loader{text-align:center}.loader .logo{margin:0 auto 18px;transform:scale(1.5);justify-content:center}.loader p{color:rgba(255,255,255,.66)}
.display,.mega,.genre-name,.rank-number,.rank-title,.spotlight-title,.studio-name,.final h1{line-height:1.12;padding-top:.04em;padding-bottom:.14em;overflow:visible}.rank-metric{white-space:normal;line-height:1.4;overflow-wrap:anywhere}.card-copy{min-height:96px}
@media(max-width:900px){.slide{padding-left:28px;padding-right:28px}.genre-layout,.rank-layout,.spotlight{grid-template-columns:1fr}.posters,.shuffle-deck,.hero-card,.rank-poster{display:none}.overview-grid{grid-template-columns:repeat(3,1fr)}.overview-card:nth-child(n+4){display:none}.rec-grid{grid-template-columns:repeat(2,minmax(120px,180px));gap:16px}.recommend{overflow:auto}.studio-wall{width:75%;opacity:.38}.summary{grid-template-columns:1fr}.brand span{display:none}}
@media(prefers-reduced-motion:reduce){*,*:before,*:after{animation-duration:.001ms!important;animation-delay:0ms!important;transition-duration:.001ms!important}.bg-layer{transform:scale(1.08)!important}}
</style></head><body tabindex="-1">
<main id="app" tabindex="-1" aria-label="Seanime Wrapped presentation"><div class="background"><div id="bgA" class="bg-layer active"></div><div id="bgB" class="bg-layer"></div><div class="veil"></div><div class="grain"></div></div>
<header class="chrome"><div id="progress" class="progress" aria-label="Slide progress"></div><div class="topline"><div class="brand"><span class="logo" aria-hidden="true"><i></i><i></i><i></i><i></i></span><span>Seanime Wrapped</span></div><div class="actions"><button id="pause" class="icon-btn" aria-label="Pause auto-advance" title="Pause / resume"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M8 5v14M16 5v14"/></svg></button><button id="close" class="icon-btn" aria-label="Close Wrapped" title="Close"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m6 6 12 12M18 6 6 18"/></svg></button></div></div></header>
<section id="stage" class="stage" aria-live="polite"></section><div class="nav-hint">← → navigate · Space pauses · Esc closes</div>
<div id="loading" class="loading"><div class="loader"><span class="logo" aria-hidden="true"><i></i><i></i><i></i><i></i></span><strong>Preparing your story</strong><p>Preparing the opening artwork.</p></div></div></main>
<script>
(()=>{"use strict";const INPUT=${payload};const S=INPUT.session;const esc=(v)=>String(v??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));const img=(v)=>esc(v||S.heroArt[0]);const artOf=(m)=>m&&(m.banner||m.cover);const arts=(items)=>[...new Set((items||[]).map(artOf).filter(Boolean))].slice(0,5);
const posters=(items)=>items.slice(0,5).map((m,i)=>'<img class="poster" style="--r:'+(-18+i*9)+'deg;--x:'+(-115+i*58)+'px;--d:'+(i*.08)+'s" data-src="'+img(m.cover)+'" alt="'+esc(m.title)+' poster">').join('');
const shufflePosters=(items)=>items.slice(0,6).map(m=>'<img class="shuffle-poster" data-src="'+img(m.cover)+'" alt="'+esc(m.title)+' poster">').join('');
const slides=[];const add=(kind,artCandidates,html,duration=6800)=>{const candidates=(Array.isArray(artCandidates)?artCandidates:[artCandidates]).filter(Boolean);slides.push({kind,arts:candidates.length?[...new Set(candidates)].slice(0,5):S.heroArt.slice(0,5),html,duration})};
const periodHeadline=INPUT.periodHeadline;
add('intro',arts(S.watched).length?arts(S.watched):S.heroArt,'<div class="slide-inner"><div class="reveal"><div class="eyebrow">Seanime Wrapped</div><h1 class="display">Your '+esc(periodHeadline)+'<br><span class="gradient">in Anime</span></h1><div class="eyebrow">'+esc(S.period.label)+'</div><p class="subtitle">Let’s see what you’ve been watching '+esc(S.period.context)+'.</p></div></div>');
if(S.enabled.watched)add('watched',arts(S.watched),'<div class="slide-inner count-layout"><div class="count-copy reveal"><div class="eyebrow">You watched</div><div class="mega gradient" data-count="'+S.watched.length+'">0</div><h2>'+S.watched.length+' anime '+esc(S.period.context)+'</h2><p class="subtitle">Every title here is grounded in dated Seanime or AniList activity.</p></div><div class="posters">'+posters(S.watched)+'</div></div>');
if(S.genres.length){const g=S.genres[0],genreAnime=S.watched.filter(m=>m.genres.includes(g.name));add('genres',arts(genreAnime),'<div class="slide-inner genre-layout"><div class="reveal"><div class="eyebrow">Your most watched genre was</div><div class="genre-name gradient">'+esc(g.name.toUpperCase())+'</div><div class="donut" style="--p:'+g.percentage+'" data-label="'+g.percentage+'%"></div></div><div class="bars">'+S.genres.map(x=>'<div class="bar-row"><b>'+esc(x.name)+'</b><div class="bar-track"><div class="bar-fill" style="--w:'+x.percentage+'%"></div></div><span>'+x.percentage+'%</span></div>').join('')+'</div></div>');}
S.topFive.slice().reverse().forEach((m)=>add('rank '+(m.rank===1?'winner':''),[artOf(m)],'<div class="slide-inner rank-layout"><img class="rank-poster" style="--accent:'+esc(m.color)+'" data-src="'+img(m.cover)+'" alt="'+esc(m.title)+' poster"><div class="reveal" style="--accent:'+esc(m.color)+'"><div class="eyebrow">Your Top 5 Anime</div><div class="rank-number">#'+m.rank+'</div><h2 class="rank-title">'+esc(m.title)+'</h2><p class="subtitle">'+esc(m.metric)+'</p></div></div>',m.rank===1?8200:5600));
if(S.topFive.length)add('overview',arts(S.topFive),'<div class="slide-inner overview"><div style="width:100%"><div class="reveal"><div class="eyebrow">The full ranking</div><h2 style="font-size:clamp(40px,5vw,74px);margin:8px 0 28px">Your Top '+S.topFive.length+'</h2></div><div class="overview-grid">'+S.topFive.map((m,i)=>'<article class="overview-card '+(m.rank===1?'winner-card':'')+'" style="--d:'+(i*.1)+'s"><span class="card-rank">#'+m.rank+'</span><img data-src="'+img(m.cover)+'" alt=""><div class="card-copy"><div class="card-title">'+esc(m.title)+'</div><div class="meta rank-metric">'+esc(m.metric)+'</div></div></article>').join('')+'</div></div></div>',7800);
if(S.enabled.ratings&&S.highestRated)add('rated',[artOf(S.highestRated)],'<div class="slide-inner spotlight"><div class="spotlight-copy reveal"><div class="eyebrow">Your highest rated anime</div><h2 class="spotlight-title">'+esc(S.highestRated.title)+'</h2><div class="score gradient">'+(INPUT.scoreLabels.highestRated===null?'—':INPUT.scoreLabels.highestRated)+'<small> / 10</small></div><p class="subtitle">'+esc((S.highestRated.genres||[]).slice(0,3).join(' · '))+(S.highestRatedStudio?' · '+esc(S.highestRatedStudio):'')+' · '+esc(S.highestRated.progress)+' episodes progress</p></div><div class="hero-card"><img data-src="'+img(S.highestRated.cover)+'" alt="'+esc(S.highestRated.title)+' poster"><div class="hero-details"><b>Your score</b><div>'+(INPUT.scoreLabels.highestRated===null?'—':INPUT.scoreLabels.highestRated)+'/10</div></div></div></div>');
if(S.topStudio)add('studio',arts(S.topStudio.anime),'<div class="slide-inner"><div class="studio-wall">'+S.topStudio.anime.slice(0,8).map(m=>'<img data-src="'+img(m.cover)+'" alt="">').join('')+'</div><div class="reveal" style="position:relative;z-index:3"><div class="eyebrow">You spent the most progress with</div><div class="studio-name gradient">'+esc(S.topStudio.name)+'</div><p class="subtitle">Based on studio metadata available for your most engaged titles.</p><div class="compact-posters">'+S.topStudio.anime.slice(0,6).map(m=>'<img data-src="'+img(m.cover)+'" alt="'+esc(m.title)+'">').join('')+'</div></div></div>');
if(S.enabled.completed)add('completed',arts(S.completed),'<div class="slide-inner count-layout"><div class="count-copy reveal"><div class="eyebrow">You completed</div><div class="mega gradient" data-count="'+S.completed.length+'">0</div><h2>'+S.completed.length+' anime '+esc(S.period.context)+'</h2></div><div class="shuffle-deck">'+shufflePosters(S.completed)+'</div></div>',INPUT.completedDuration);
if(S.enabled.ratings)add('average',S.highestRated?[artOf(S.highestRated)]:S.heroArt,'<div class="slide-inner final"><div class="reveal"><div class="eyebrow">Your average score</div><div class="display gradient">'+(INPUT.scoreLabels.average===null?'—':INPUT.scoreLabels.average)+'</div><p class="subtitle" style="margin:auto">'+(S.averageScore===null?'No anime in this period had a user score. That’s okay—your recap stays honest.':'Calculated only from scores you gave, never AniList community scores.')+'</p></div></div>');
if(S.activeDay)add('day',arts(S.watched),'<div class="slide-inner"><div class="reveal"><div class="eyebrow">Your most active saved-watch weekday</div><h2 class="display gradient">'+esc(S.activeDay.label)+'</h2><p class="subtitle">'+S.activeDay.count+' title'+(S.activeDay.count===1?'':'s')+' had their latest saved watch record on this weekday.</p><p class="meta" style="max-width:620px;margin-top:25px">'+esc(S.activeDay.interpretation)+'</p></div></div>');
if(S.enabled.recommendations&&S.recommendations.length)add('recommend',arts(S.recommendations),'<div class="slide-inner recommend"><div style="width:100%"><div class="recommend-head"><div><div class="eyebrow">What comes next</div><h2>Most likely next watch</h2></div><span class="meta">Taste-fit shortlist</span></div><div class="rec-grid">'+S.recommendations.map((m,i)=>'<button type="button" class="rec-card" data-media-id="'+m.mediaId+'" aria-label="Open '+esc(m.title)+' in Seanime" style="--i:'+i+'"><span class="rec-rank">'+(i+1)+'</span><img data-src="'+img(m.cover)+'" alt=""><div class="rec-copy"><b>'+esc(m.title)+'</b><span class="rec-rating">★ '+(m.globalScore?(m.globalScore/10).toFixed(1):'—')+' AniList</span><span class="reason">'+esc(m.reason)+'</span></div></button>').join('')+'</div></div></div>',10000);
add('final',arts(S.topFive),'<div class="slide-inner final"><div class="reveal"><div class="eyebrow">'+esc(S.period.label)+' in a nutshell</div><h1>That was your<br><span class="gradient">Seanime Wrapped</span></h1><div class="summary">'+S.summary.map(x=>'<div>'+esc(x)+'</div>').join('')+'</div><div class="thanks">Thanks for watching.</div></div></div>',12000);
const FALLBACK="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 1200 675'%3E%3Cdefs%3E%3ClinearGradient id='g'%3E%3Cstop stop-color='%234c5cff'/%3E%3Cstop offset='.55' stop-color='%23bd42d8'/%3E%3Cstop offset='1' stop-color='%23101525'/%3E%3C/linearGradient%3E%3C/defs%3E%3Crect width='1200' height='675' fill='%23070a14'/%3E%3Ccircle cx='380' cy='270' r='330' fill='url(%23g)' opacity='.8'/%3E%3C/svg%3E";const PAUSE_ICON='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M8 5v14M16 5v14"/></svg>',PLAY_ICON='<svg viewBox="0 0 24 24" aria-hidden="true"><path class="filled" d="m8 5 11 7-11 7z"/></svg>';const MAX_PRELOAD_AHEAD=2;const failedArt=new Set(),artLoads=new Map(),handledKeys=new WeakSet();const app=document.getElementById('app'),stage=document.getElementById('stage'),progress=document.getElementById('progress'),loading=document.getElementById('loading'),pause=document.getElementById('pause');let index=0,paused=!INPUT.settings.autoAdvance,elapsed=0,last=0,raf=0,closed=false,bgFlip=false,backgroundIndex=0,shuffleCycle=-1;let effectRafs=[];
stage.innerHTML=slides.map((s,i)=>'<article class="slide '+esc(s.kind)+'" data-index="'+i+'">'+s.html+'</article>').join('');progress.innerHTML=slides.map(()=>'<span class="segment"><i></i></span>').join('');
function requestEffect(fn){const id=requestAnimationFrame(t=>{effectRafs=effectRafs.filter(value=>value!==id);fn(t)});effectRafs.push(id);return id}function clearEffects(){effectRafs.forEach(cancelAnimationFrame);effectRafs=[]}function resolvedArt(url){return !url||failedArt.has(url)?FALLBACK:url}function setBackground(url){const incoming=document.getElementById(bgFlip?'bgA':'bgB'),outgoing=document.getElementById(bgFlip?'bgB':'bgA');const clean=String(resolvedArt(url)).split('"').join('').split(String.fromCharCode(92)).join('');incoming.style.backgroundImage='url("'+clean+'")';incoming.classList.add('active');outgoing.classList.remove('active');bgFlip=!bgFlip}
function loadArtwork(url){const source=String(url||'');if(!source||failedArt.has(source))return Promise.resolve(FALLBACK);if(artLoads.has(source))return artLoads.get(source);const pending=new Promise(resolve=>{const image=new Image();const finish=(result)=>{clearTimeout(timer);image.onload=null;image.onerror=null;resolve(result)};const timer=setTimeout(()=>{failedArt.add(source);image.src='';finish(FALLBACK)},6000);image.onload=()=>finish(source);image.onerror=()=>{failedArt.add(source);finish(FALLBACK)};image.src=source});artLoads.set(source,pending);return pending}
function prepareSlide(slideIndex){const record=slides[slideIndex],root=document.querySelector('.slide[data-index="'+slideIndex+'"]');if(!record||!root)return Promise.resolve();const images=[...root.querySelectorAll('img[data-src]')];return Promise.all([...record.arts.map(loadArtwork),...images.map(image=>loadArtwork(image.dataset.src))]).then(results=>{const offset=record.arts.length;images.forEach((image,i)=>{image.src=results[offset+i]||FALLBACK;image.removeAttribute('data-src');image.addEventListener('error',()=>{image.src=FALLBACK},{once:true})})})}
function primeWindow(center){const pending=[];for(let offset=0;offset<=MAX_PRELOAD_AHEAD;offset++){const slideIndex=center+offset;if(slideIndex<slides.length)pending.push(prepareSlide(slideIndex))}return Promise.all(pending)}
function countUp(root){clearEffects();root.querySelectorAll('[data-count]').forEach(el=>{const target=Number(el.dataset.count||0);if(matchMedia('(prefers-reduced-motion: reduce)').matches){el.textContent=target;return}const start=performance.now();const step=t=>{if(closed)return;const p=Math.min(1,(t-start)/900);el.textContent=Math.round(target*(1-Math.pow(1-p,3)));if(p<1)requestEffect(step)};requestEffect(step)})}
function shuffleCompleted(root,cycle){const posters=[...root.querySelectorAll('.shuffle-poster')],count=posters.length;if(!count)return;posters.forEach((poster,i)=>{const slot=(i+cycle)%count,position=count===1?50:8+(slot*84/(count-1)),foreground=slot===Math.floor((count-1)/2);poster.style.left=position+'%';poster.style.zIndex=String(foreground?20:slot+1);poster.style.filter=foreground?'brightness(1.08)':'brightness(.72)';poster.style.transform='translate(-50%,-50%) rotate('+(slot-(count-1)/2)*4+'deg) scale('+(foreground?1.1:.9)+')'})}
function show(next){index=Math.max(0,Math.min(slides.length-1,next));elapsed=0;last=performance.now();backgroundIndex=0;shuffleCycle=-1;primeWindow(index);document.querySelectorAll('.slide').forEach((el,i)=>el.classList.toggle('active',i===index));setBackground(slides[index].arts[0]);const root=document.querySelector('.slide[data-index="'+index+'"]');countUp(root);if(slides[index].kind==='completed'){shuffleCycle=0;shuffleCompleted(root,0)}updateProgress(0)}
function updateProgress(frac){[...progress.children].forEach((seg,i)=>seg.firstElementChild.style.width=(i<index?100:i>index?0:frac*100)+'%')}
function updatePause(){pause.innerHTML=paused?PLAY_ICON:PAUSE_ICON;pause.setAttribute('aria-label',paused?'Resume auto-advance':'Pause auto-advance')}
function tick(now){if(closed)return;if(!last)last=now;if(!paused){elapsed+=now-last;const slide=slides[index],cycle=Math.floor(elapsed/3000);if(slide.arts.length>1&&cycle!==backgroundIndex){backgroundIndex=cycle%slide.arts.length;setBackground(slide.arts[backgroundIndex])}if(slide.kind==='completed'&&cycle!==shuffleCycle){shuffleCycle=cycle;shuffleCompleted(document.querySelector('.slide[data-index="'+index+'"]'),cycle)}const fraction=Math.min(1,elapsed/slide.duration);updateProgress(fraction);if(fraction>=1&&index<slides.length-1){show(index+1)}else if(fraction>=1){paused=true;updatePause()}}last=now;raf=requestAnimationFrame(tick)}
function togglePause(){paused=!paused;updatePause();last=performance.now()}
function focusViewer(){window.focus();try{app.focus({preventScroll:true})}catch{app.focus()}}
function cleanup(){cancelAnimationFrame(raf);clearEffects();document.removeEventListener('keydown',onKey,true);window.removeEventListener('keydown',onKey);app.removeEventListener('click',focusViewer,true);stage.removeEventListener('click',onStage)}
function close(){if(closed)return;closed=true;app.classList.add('closing');cleanup();window.webview?.send('close',{})}
function onKey(e){if(handledKeys.has(e))return;if(e.target.closest?.('.rec-card')&&(e.key==='Enter'||e.code==='Space'||e.key===' '))return;handledKeys.add(e);if(e.key==='ArrowRight'){e.preventDefault();show(index+1)}else if(e.key==='ArrowLeft'){e.preventDefault();show(index-1)}else if(e.key==='Escape'){e.preventDefault();close()}else if(e.code==='Space'||e.key===' '){e.preventDefault();togglePause()}}
function onStage(e){const card=e.target.closest('.rec-card');if(card){const mediaId=Number(card.dataset.mediaId||0);if(mediaId>0){closed=true;cleanup();window.webview?.send('open-anime',{mediaId})}return}if(e.target.closest('button'))return;show(index+(e.clientX<innerWidth/2?-1:1))}
document.getElementById('close').addEventListener('click',close);pause.addEventListener('click',togglePause);document.addEventListener('keydown',onKey,true);window.addEventListener('keydown',onKey);app.addEventListener('click',focusViewer,true);stage.addEventListener('click',onStage);window.addEventListener('pagehide',cleanup,{once:true});window.focus();updatePause();
primeWindow(0).then(()=>{loading.classList.add('hidden');show(0);focusViewer();raf=requestAnimationFrame(tick)});
})();
</script></body></html>`;
  }

  return { documentFor, completedSlideDuration };
}

export type WrappedViewer = ReturnType<typeof createViewer>;
