import type { WrappedSession, WrappedSettings } from "./domain";

export interface ViewerInput {
  session: WrappedSession;
  settings: WrappedSettings;
  audioSource: string;
  audioLabel: string;
}

export function createViewer() {
  function safeJson(value: unknown): string {
    return JSON.stringify(value).replace(/</g, "\\u003c").replace(/>/g, "\\u003e").replace(/&/g, "\\u0026");
  }

  function documentFor(input: ViewerInput): string {
    const payload = safeJson(input);
    return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>Seanime Wrapped</title>
<style>
:root{color-scheme:dark;--pink:#f14fd9;--violet:#8b5cf6;--blue:#5d79ff;--glass:rgba(10,14,29,.55);--line:rgba(255,255,255,.17);--ease:cubic-bezier(.22,.8,.2,1)}
*{box-sizing:border-box}html,body{width:100%;height:100%;margin:0;overflow:hidden;background:#060914;color:#fff;font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif}button{font:inherit;color:inherit}
#app{position:fixed;inset:0;isolation:isolate;background:#070a14;opacity:1;transition:opacity .32s ease}.closing{opacity:0!important}
.background,.bg-layer,.veil,.grain{position:absolute;inset:-4%}.bg-layer{background:center/cover no-repeat;filter:blur(16px) saturate(1.22);transform:scale(1.08);opacity:0;transition:opacity 1s ease,transform 8s var(--ease)}.bg-layer.active{opacity:.68;transform:scale(1.13)}
.veil{inset:0;background:radial-gradient(circle at 78% 30%,transparent 0,rgba(3,6,18,.18) 32%,rgba(3,6,18,.82) 78%),linear-gradient(90deg,rgba(4,7,18,.94),rgba(4,7,18,.45) 58%,rgba(4,7,18,.78));z-index:1}.grain{z-index:2;opacity:.08;pointer-events:none;background-image:url("data:image/svg+xml,%3Csvg viewBox='0 0 180 180' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='.8' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='.7'/%3E%3C/svg%3E")}
.chrome{position:absolute;z-index:20;top:0;left:0;right:0;padding:max(18px,2.3vh) clamp(22px,4vw,74px);display:grid;gap:15px}.progress{display:flex;gap:7px}.segment{height:4px;flex:1;border-radius:99px;background:rgba(255,255,255,.23);overflow:hidden}.segment>i{display:block;width:0;height:100%;background:#fff;box-shadow:0 0 12px rgba(255,255,255,.65)}
.topline{display:flex;align-items:center;justify-content:space-between}.brand{display:flex;align-items:center;gap:12px;font-weight:760;letter-spacing:-.02em}.logo{display:flex;align-items:end;gap:3px;height:27px}.logo i{display:block;width:6px;border-radius:7px;background:linear-gradient(180deg,#ff99a8,#e84fe0 55%,#596dff)}.logo i:nth-child(1){height:12px}.logo i:nth-child(2){height:21px}.logo i:nth-child(3){height:27px}.logo i:nth-child(4){height:17px}.actions{display:flex;gap:9px}.icon-btn{width:42px;height:42px;border:1px solid rgba(255,255,255,.13);border-radius:50%;background:rgba(5,8,20,.52);backdrop-filter:blur(14px);display:grid;place-items:center;cursor:pointer;transition:transform .2s ease,background .2s}.icon-btn:hover{background:rgba(255,255,255,.13);transform:scale(1.05)}.icon-btn:focus-visible{outline:3px solid #fff;outline-offset:3px}
.stage{position:absolute;inset:0;z-index:5}.slide{position:absolute;inset:0;padding:clamp(100px,14vh,145px) clamp(34px,8vw,140px) clamp(38px,7vh,75px);display:none;opacity:0;transform:scale(1.025);transition:opacity .55s ease,transform .7s var(--ease)}.slide.active{display:flex;opacity:1;transform:scale(1)}
.slide-inner{width:min(1420px,100%);height:100%;margin:auto;display:flex;align-items:center;position:relative}.eyebrow{font-size:clamp(12px,1vw,16px);text-transform:uppercase;letter-spacing:.16em;color:#d8d9ff;font-weight:750}.display{font-size:clamp(58px,8.4vw,138px);line-height:.85;letter-spacing:-.065em;margin:14px 0 24px;max-width:920px}.gradient{background:linear-gradient(110deg,#fff 8%,#efc8ff 35%,#ec52d7 70%,#7c8fff);-webkit-background-clip:text;background-clip:text;color:transparent}.subtitle{font-size:clamp(17px,1.6vw,27px);line-height:1.45;color:rgba(255,255,255,.78);max-width:620px}.reveal>*{opacity:0;transform:translateY(28px);filter:blur(8px)}.active .reveal>*{animation:reveal .72s var(--ease) forwards}.active .reveal>*:nth-child(2){animation-delay:.1s}.active .reveal>*:nth-child(3){animation-delay:.2s}.active .reveal>*:nth-child(4){animation-delay:.3s}@keyframes reveal{to{opacity:1;transform:none;filter:none}}
.count-layout{justify-content:space-between;gap:6vw}.count-copy{max-width:620px}.mega{font-size:clamp(100px,18vw,275px);line-height:.7;font-weight:900;letter-spacing:-.08em;text-shadow:0 0 50px rgba(235,70,215,.3)}.posters{position:relative;width:min(42vw,610px);height:min(64vh,620px)}.poster{position:absolute;left:50%;top:50%;width:clamp(130px,15vw,220px);aspect-ratio:2/3;object-fit:cover;border-radius:18px;border:1px solid rgba(255,255,255,.3);box-shadow:0 30px 80px rgba(0,0,0,.55);transform:translate(-50%,-50%) rotate(var(--r)) translateX(var(--x));transition:transform 1s var(--ease);animation:posterIn .9s var(--ease) both;animation-delay:var(--d)}@keyframes posterIn{from{opacity:0;transform:translate(-50%,-40%) rotate(0) scale(.65)}}
.genre-layout{display:grid;grid-template-columns:minmax(300px,.8fr) minmax(400px,1.2fr);gap:9vw;align-items:center}.genre-name{font-size:clamp(64px,9vw,150px);font-weight:900;letter-spacing:-.06em;line-height:.86}.donut{width:min(24vw,310px);aspect-ratio:1;border-radius:50%;display:grid;place-items:center;margin-top:30px;background:conic-gradient(var(--pink) calc(var(--p)*1%),rgba(255,255,255,.13) 0);box-shadow:0 0 55px rgba(230,65,214,.25)}.donut:after{content:attr(data-label);width:67%;aspect-ratio:1;border-radius:50%;background:rgba(7,10,22,.9);display:grid;place-items:center;font-size:clamp(30px,4vw,60px);font-weight:850}.bars{display:grid;gap:18px}.bar-row{display:grid;grid-template-columns:130px 1fr 48px;gap:18px;align-items:center}.bar-track{height:12px;background:rgba(255,255,255,.1);border-radius:99px;overflow:hidden}.bar-fill{height:100%;width:0;border-radius:inherit;background:linear-gradient(90deg,var(--blue),var(--pink));transition:width 1.2s var(--ease) .25s}.active .bar-fill{width:var(--w)}
.rank-layout{display:grid;grid-template-columns:minmax(300px,.9fr) minmax(420px,1.1fr);gap:7vw}.rank-poster{justify-self:end;width:min(31vw,440px);max-height:66vh;aspect-ratio:2/3;object-fit:cover;border-radius:26px;border:1px solid rgba(255,255,255,.25);box-shadow:0 40px 100px rgba(0,0,0,.6),0 0 70px color-mix(in srgb,var(--accent) 35%,transparent);animation:rankPoster 1s var(--ease) both}@keyframes rankPoster{from{opacity:0;transform:translateX(-60px) rotate(-5deg) scale(.88)}}.rank-number{font-size:clamp(82px,13vw,220px);font-weight:950;letter-spacing:-.08em;line-height:.72;color:var(--accent)}.rank-title{font-size:clamp(38px,5vw,78px);line-height:.96;letter-spacing:-.045em;margin:26px 0 18px}.winner .rank-poster{width:min(30vw,440px);box-shadow:0 40px 110px rgba(0,0,0,.65),0 0 120px rgba(241,79,217,.45)}.winner .rank-number{background:linear-gradient(100deg,#fff,#ff92e9,#7b8cff);-webkit-background-clip:text;color:transparent}
.overview{align-items:flex-end}.overview-grid{width:100%;display:grid;grid-template-columns:repeat(5,1fr);align-items:end;gap:14px}.overview-card{position:relative;min-width:0;border-radius:18px;overflow:hidden;border:1px solid rgba(255,255,255,.18);background:var(--glass);box-shadow:0 20px 60px rgba(0,0,0,.35);animation:cardUp .7s var(--ease) both;animation-delay:var(--d)}.overview-card:first-child{transform:translateY(-28px);border-color:rgba(255,114,219,.7)}@keyframes cardUp{from{opacity:0;transform:translateY(60px)}}.overview-card img{display:block;width:100%;aspect-ratio:2/3;object-fit:cover}.card-copy{padding:14px}.card-rank{position:absolute;top:12px;left:12px;font-size:30px;font-weight:900;text-shadow:0 3px 12px #000}.card-title{font-weight:750;white-space:nowrap;text-overflow:ellipsis;overflow:hidden}.meta{font-size:13px;color:rgba(255,255,255,.62);margin-top:5px}
.spotlight{display:grid;grid-template-columns:minmax(300px,1fr) minmax(310px,.9fr);gap:7vw}.spotlight-copy{align-self:center}.spotlight-title{font-size:clamp(46px,6.2vw,102px);line-height:.93;letter-spacing:-.055em;margin:15px 0}.hero-card{position:relative;justify-self:end;width:min(34vw,470px);height:min(66vh,650px);border-radius:28px;overflow:hidden;border:1px solid rgba(255,255,255,.22);box-shadow:0 40px 100px rgba(0,0,0,.58)}.hero-card img{width:100%;height:100%;object-fit:cover}.hero-card:after{content:"";position:absolute;inset:45% 0 0;background:linear-gradient(transparent,rgba(5,7,16,.96))}.hero-details{position:absolute;z-index:2;left:28px;right:28px;bottom:26px}.score{font-size:clamp(62px,8vw,120px);font-weight:930;letter-spacing:-.07em}.score small{font-size:.25em;color:rgba(255,255,255,.7);letter-spacing:0}
.studio-wall{position:absolute;right:0;width:55%;height:74%;display:grid;grid-template-columns:repeat(4,1fr);gap:12px;opacity:.78;mask-image:linear-gradient(90deg,transparent,#000 25%)}.studio-wall img{width:100%;height:100%;min-height:0;object-fit:cover;border-radius:16px}.studio-name{position:relative;z-index:2;font-size:clamp(70px,11vw,180px);font-weight:930;letter-spacing:-.07em;line-height:.8;max-width:850px}.compact-posters{display:flex;gap:10px;margin-top:28px}.compact-posters img{width:80px;aspect-ratio:2/3;object-fit:cover;border-radius:10px;border:1px solid rgba(255,255,255,.25)}
.recommend{align-items:flex-start;padding-top:2vh}.recommend-head{display:flex;justify-content:space-between;align-items:end;margin-bottom:20px}.recommend-head h2{font-size:clamp(36px,4.2vw,66px);margin:0;letter-spacing:-.045em}.rec-grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:12px}.rec-card{height:min(30vh,260px);position:relative;overflow:hidden;border:1px solid rgba(255,255,255,.16);border-radius:15px;background:rgba(9,13,27,.7);animation:cardUp .6s var(--ease) both;animation-delay:calc(var(--i)*55ms)}.rec-card img{width:100%;height:100%;object-fit:cover}.rec-card:after{content:"";position:absolute;inset:25% 0 0;background:linear-gradient(transparent,rgba(5,8,18,.98))}.rec-copy{position:absolute;z-index:2;left:13px;right:13px;bottom:11px}.rec-rank{position:absolute;z-index:3;top:9px;left:10px;width:28px;height:28px;border-radius:8px;background:rgba(6,8,18,.78);display:grid;place-items:center;font-weight:850}.reason{display:inline-block;font-size:10px;padding:4px 7px;border-radius:99px;background:rgba(126,94,255,.7);margin-top:6px;white-space:nowrap;max-width:100%;overflow:hidden;text-overflow:ellipsis}
.final{align-items:center;justify-content:center;text-align:center}.final h1{font-size:clamp(50px,7vw,110px);line-height:.9;letter-spacing:-.06em;margin:12px 0 35px}.summary{display:grid;grid-template-columns:repeat(2,minmax(260px,1fr));gap:10px;width:min(850px,90vw);text-align:left}.summary div{padding:16px 20px;border:1px solid var(--line);border-radius:14px;background:rgba(9,12,26,.45);backdrop-filter:blur(12px)}.thanks{margin-top:34px;font-size:clamp(18px,2vw,28px);color:#f0cbff}
.nav-hint{position:absolute;z-index:15;bottom:22px;left:50%;transform:translateX(-50%);font-size:12px;color:rgba(255,255,255,.45);pointer-events:none}.loading{position:absolute;inset:0;z-index:30;display:grid;place-items:center;background:#080b17;transition:opacity .45s}.loading.hidden{opacity:0;pointer-events:none}.loader{text-align:center}.loader .logo{margin:0 auto 18px;transform:scale(1.5);justify-content:center}.loader p{color:rgba(255,255,255,.66)}.sound-prompt{position:absolute;z-index:25;right:clamp(22px,4vw,74px);bottom:26px;border:1px solid var(--line);border-radius:99px;background:rgba(7,10,22,.7);padding:10px 15px;display:none}.sound-prompt.show{display:block}
@media(max-width:900px){.slide{padding-left:28px;padding-right:28px}.genre-layout,.rank-layout,.spotlight{grid-template-columns:1fr}.posters,.hero-card,.rank-poster{display:none}.overview-grid{grid-template-columns:repeat(3,1fr)}.overview-card:nth-child(n+4){display:none}.rec-grid{grid-template-columns:repeat(2,1fr)}.rec-card{height:24vh}.recommend{overflow:auto}.studio-wall{width:75%;opacity:.38}.summary{grid-template-columns:1fr}.brand span{display:none}}
@media(prefers-reduced-motion:reduce){*,*:before,*:after{animation-duration:.001ms!important;animation-delay:0ms!important;transition-duration:.001ms!important}.bg-layer{transform:scale(1.08)!important}}
</style></head><body>
<main id="app" aria-label="Seanime Wrapped presentation"><div class="background"><div id="bgA" class="bg-layer active"></div><div id="bgB" class="bg-layer"></div><div class="veil"></div><div class="grain"></div></div>
<header class="chrome"><div id="progress" class="progress" aria-label="Slide progress"></div><div class="topline"><div class="brand"><span class="logo" aria-hidden="true"><i></i><i></i><i></i><i></i></span><span>Seanime Wrapped</span></div><div class="actions"><button id="pause" class="icon-btn" aria-label="Pause auto-advance" title="Pause / resume">Ⅱ</button><button id="mute" class="icon-btn" aria-label="Mute soundtrack" title="Mute / unmute">♪</button><button id="close" class="icon-btn" aria-label="Close Wrapped" title="Close">×</button></div></div></header>
<section id="stage" class="stage" aria-live="polite"></section><div class="nav-hint">← → navigate · Space pauses · Esc closes</div><button id="soundPrompt" class="sound-prompt">Click to enable ${input.audioLabel ? "“" + input.audioLabel + "”" : "sound"}</button>
<div id="loading" class="loading"><div class="loader"><span class="logo" aria-hidden="true"><i></i><i></i><i></i><i></i></span><strong>Preparing your story</strong><p>Preloading artwork — navigation stays network-free.</p></div></div></main>
<script>
(()=>{"use strict";const INPUT=${payload};const S=INPUT.session;const esc=(v)=>String(v??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));const img=(v)=>esc(v||S.heroArt[0]);
const posters=(items)=>items.slice(0,5).map((m,i)=>'<img class="poster" style="--r:'+(-18+i*9)+'deg;--x:'+(-115+i*58)+'px;--d:'+(i*.08)+'s" src="'+img(m.cover)+'" alt="'+esc(m.title)+' poster">').join('');
const slides=[];const add=(kind,art,html,duration=6800)=>slides.push({kind,art:art||S.heroArt[0],html,duration});
add('intro',S.heroArt[0],'<div class="slide-inner"><div class="reveal"><div class="eyebrow">'+esc(S.period.label)+'</div><h1 class="display">Your <span class="gradient">'+esc(S.period.label.replace(/\\s+\\d{4}$/,''))+'</span><br>in Anime</h1><p class="subtitle">Let’s see what you’ve been watching '+esc(S.period.context)+'.</p></div></div>');
if(S.enabled.watched)add('watched',S.watched[0]?.banner,'<div class="slide-inner count-layout"><div class="count-copy reveal"><div class="eyebrow">You watched</div><div class="mega gradient" data-count="'+S.watched.length+'">0</div><h2>'+S.watched.length+' anime '+esc(S.period.context)+'</h2><p class="subtitle">Every title here is grounded in saved Seanime watch activity or a dated AniList entry update.</p></div><div class="posters">'+posters(S.watched)+'</div></div>');
if(S.genres.length){const g=S.genres[0];add('genres',S.watched.find(m=>m.genres.includes(g.name))?.banner,'<div class="slide-inner genre-layout"><div class="reveal"><div class="eyebrow">Your most watched genre was</div><div class="genre-name gradient">'+esc(g.name.toUpperCase())+'</div><div class="donut" style="--p:'+g.percentage+'" data-label="'+g.percentage+'%"></div></div><div class="bars">'+S.genres.map(x=>'<div class="bar-row"><b>'+esc(x.name)+'</b><div class="bar-track"><div class="bar-fill" style="--w:'+x.percentage+'%"></div></div><span>'+x.percentage+'%</span></div>').join('')+'</div></div>');}
S.topFive.slice().reverse().forEach((m)=>add('rank '+(m.rank===1?'winner':''),m.banner,'<div class="slide-inner rank-layout"><img class="rank-poster" style="--accent:'+esc(m.color)+'" src="'+img(m.cover)+'" alt="'+esc(m.title)+' poster"><div class="reveal" style="--accent:'+esc(m.color)+'"><div class="eyebrow">Your Top 5 Anime</div><div class="rank-number">#'+m.rank+'</div><h2 class="rank-title">'+esc(m.title)+'</h2><p class="subtitle">'+esc(m.metric)+'</p></div></div>',m.rank===1?8200:5600));
if(S.topFive.length)add('overview',S.topFive[0].banner,'<div class="slide-inner overview"><div style="width:100%"><div class="reveal"><div class="eyebrow">The full ranking</div><h2 style="font-size:clamp(40px,5vw,74px);margin:8px 0 28px">Your Top '+S.topFive.length+'</h2></div><div class="overview-grid">'+S.topFive.map((m,i)=>'<article class="overview-card" style="--d:'+(i*.1)+'s"><span class="card-rank">#'+m.rank+'</span><img src="'+img(m.cover)+'" alt=""><div class="card-copy"><div class="card-title">'+esc(m.title)+'</div><div class="meta">'+esc(m.metric)+'</div></div></article>').join('')+'</div></div></div>',7800);
if(S.enabled.ratings&&S.highestRated)add('rated',S.highestRated.banner,'<div class="slide-inner spotlight"><div class="spotlight-copy reveal"><div class="eyebrow">Your highest rated anime</div><h2 class="spotlight-title">'+esc(S.highestRated.title)+'</h2><div class="score gradient">'+Number(S.highestRated.userScore).toFixed(1)+'<small> / 10</small></div><p class="subtitle">'+esc((S.highestRated.genres||[]).slice(0,3).join(' · '))+(S.highestRatedStudio?' · '+esc(S.highestRatedStudio):'')+' · '+esc(S.highestRated.progress)+' episodes progress</p></div><div class="hero-card"><img src="'+img(S.highestRated.cover)+'" alt="'+esc(S.highestRated.title)+' poster"><div class="hero-details"><b>Your score</b><div>'+Number(S.highestRated.userScore).toFixed(1)+'/10</div></div></div></div>');
if(S.topStudio)add('studio',S.topStudio.anime[0]?.banner,'<div class="slide-inner"><div class="studio-wall">'+S.topStudio.anime.slice(0,8).map(m=>'<img src="'+img(m.cover)+'" alt="">').join('')+'</div><div class="reveal" style="position:relative;z-index:3"><div class="eyebrow">You spent the most progress with</div><div class="studio-name gradient">'+esc(S.topStudio.name)+'</div><p class="subtitle">Based on studio metadata available for your most engaged titles.</p><div class="compact-posters">'+S.topStudio.anime.slice(0,6).map(m=>'<img src="'+img(m.cover)+'" alt="'+esc(m.title)+'">').join('')+'</div></div></div>');
if(S.enabled.completed)add('completed',S.completed[0]?.banner,'<div class="slide-inner count-layout"><div class="count-copy reveal"><div class="eyebrow">You completed</div><div class="mega gradient" data-count="'+S.completed.length+'">0</div><h2>'+S.completed.length+' anime '+esc(S.period.context)+'</h2></div><div class="posters">'+posters(S.completed)+'</div></div>');
if(S.enabled.ratings)add('average',S.highestRated?.banner,'<div class="slide-inner final"><div class="reveal"><div class="eyebrow">Your average score</div><div class="display gradient">'+(S.averageScore===null?'—':Number(S.averageScore).toFixed(1))+'</div><p class="subtitle" style="margin:auto">'+(S.averageScore===null?'No anime in this period had a user score. That’s okay—your recap stays honest.':'Calculated only from scores you gave, never AniList community scores.')+'</p></div></div>');
if(S.activeDay)add('day',S.heroArt[1],'<div class="slide-inner"><div class="reveal"><div class="eyebrow">Your most active saved-watch weekday</div><h2 class="display gradient">'+esc(S.activeDay.label)+'</h2><p class="subtitle">'+S.activeDay.count+' title'+(S.activeDay.count===1?'':'s')+' had their latest saved watch record on this weekday.</p><p class="meta" style="max-width:620px;margin-top:25px">'+esc(S.activeDay.interpretation)+'</p></div></div>');
if(S.enabled.recommendations&&S.recommendations.length)add('recommend',S.recommendations[0].banner,'<div class="slide-inner recommend"><div style="width:100%"><div class="recommend-head"><div><div class="eyebrow">What comes next</div><h2>Most likely next watch</h2></div><span class="meta">Taste-fit shortlist</span></div><div class="rec-grid">'+S.recommendations.map((m,i)=>'<article class="rec-card" style="--i:'+i+'"><span class="rec-rank">'+(i+1)+'</span><img src="'+img(m.cover)+'" alt=""><div class="rec-copy"><b>'+esc(m.title)+'</b><div class="meta">'+(m.globalScore?('★ '+(m.globalScore/10).toFixed(1)+' · '):'')+esc((m.genres||[]).slice(0,2).join(', '))+'</div><span class="reason">'+esc(m.reason)+'</span></div></article>').join('')+'</div></div></div>',10000);
add('final',S.topFive[0]?.banner,'<div class="slide-inner final"><div class="reveal"><div class="eyebrow">'+esc(S.period.label)+' in a nutshell</div><h1>That was your<br><span class="gradient">Seanime Wrapped</span></h1><div class="summary">'+S.summary.map(x=>'<div>'+esc(x)+'</div>').join('')+'</div><div class="thanks">Thanks for watching.</div></div></div>',12000);
const FALLBACK="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 1200 675'%3E%3Cdefs%3E%3ClinearGradient id='g'%3E%3Cstop stop-color='%234c5cff'/%3E%3Cstop offset='.55' stop-color='%23bd42d8'/%3E%3Cstop offset='1' stop-color='%23101525'/%3E%3C/linearGradient%3E%3C/defs%3E%3Crect width='1200' height='675' fill='%23070a14'/%3E%3Ccircle cx='380' cy='270' r='330' fill='url(%23g)' opacity='.8'/%3E%3C/svg%3E";const failedArt=new Set();const app=document.getElementById('app'),stage=document.getElementById('stage'),progress=document.getElementById('progress'),loading=document.getElementById('loading'),mute=document.getElementById('mute'),pause=document.getElementById('pause'),prompt=document.getElementById('soundPrompt');let index=0,paused=!INPUT.settings.autoAdvance,elapsed=0,last=0,raf=0,closed=false,bgFlip=false,audio=null;let effectRafs=[];
stage.innerHTML=slides.map((s,i)=>'<article class="slide '+esc(s.kind)+'" data-index="'+i+'">'+s.html+'</article>').join('');progress.innerHTML=slides.map(()=>'<span class="segment"><i></i></span>').join('');
function requestEffect(fn){const id=requestAnimationFrame(t=>{effectRafs=effectRafs.filter(value=>value!==id);fn(t)});effectRafs.push(id);return id}function clearEffects(){effectRafs.forEach(cancelAnimationFrame);effectRafs=[]}function resolvedArt(url){return !url||failedArt.has(url)?FALLBACK:url}function setBackground(url){const incoming=document.getElementById(bgFlip?'bgA':'bgB'),outgoing=document.getElementById(bgFlip?'bgB':'bgA');const clean=String(resolvedArt(url)).split('"').join('').split(String.fromCharCode(92)).join('');incoming.style.backgroundImage='url("'+clean+'")';incoming.classList.add('active');outgoing.classList.remove('active');bgFlip=!bgFlip}
function countUp(root){clearEffects();root.querySelectorAll('[data-count]').forEach(el=>{const target=Number(el.dataset.count||0);if(matchMedia('(prefers-reduced-motion: reduce)').matches){el.textContent=target;return}const start=performance.now();const step=t=>{if(closed)return;const p=Math.min(1,(t-start)/900);el.textContent=Math.round(target*(1-Math.pow(1-p,3)));if(p<1)requestEffect(step)};requestEffect(step)})}
function show(next){index=Math.max(0,Math.min(slides.length-1,next));elapsed=0;last=performance.now();document.querySelectorAll('.slide').forEach((el,i)=>el.classList.toggle('active',i===index));setBackground(slides[index].art);countUp(document.querySelector('.slide[data-index="'+index+'"]'));updateProgress(0)}
function updateProgress(frac){[...progress.children].forEach((seg,i)=>seg.firstElementChild.style.width=(i<index?100:i>index?0:frac*100)+'%')}
function tick(now){if(closed)return;if(!last)last=now;if(!paused){elapsed+=now-last;const duration=slides[index].duration;const fraction=Math.min(1,elapsed/duration);updateProgress(fraction);if(fraction>=1&&index<slides.length-1){show(index+1)}else if(fraction>=1){paused=true;pause.textContent='▶';pause.setAttribute('aria-label','Resume auto-advance')}}last=now;raf=requestAnimationFrame(tick)}
function togglePause(){paused=!paused;pause.textContent=paused?'▶':'Ⅱ';pause.setAttribute('aria-label',paused?'Resume auto-advance':'Pause auto-advance');last=performance.now()}
function setupAudio(){if(!INPUT.audioSource){mute.textContent='×';mute.setAttribute('aria-label','No soundtrack available');return}audio=new Audio(INPUT.audioSource);audio.loop=true;audio.volume=0;audio.muted=false;const wanted=Math.max(0,Math.min(1,Number(INPUT.settings.volume||30)/100));const play=()=>audio.play().then(()=>{prompt.classList.remove('show');const begin=performance.now();const fade=t=>{if(!audio||closed)return;audio.volume=Math.min(wanted,wanted*((t-begin)/900));if(audio.volume<wanted)requestEffect(fade)};requestEffect(fade)}).catch(()=>prompt.classList.add('show'));play();prompt.addEventListener('click',play)}
function toggleMute(){if(!audio)return;audio.muted=!audio.muted;mute.textContent=audio.muted?'♩':'♪';mute.setAttribute('aria-label',audio.muted?'Unmute soundtrack':'Mute soundtrack')}
function cleanup(){cancelAnimationFrame(raf);clearEffects();window.removeEventListener('keydown',onKey);stage.removeEventListener('click',onStage);prompt.replaceWith(prompt.cloneNode(true));if(audio){audio.volume=0;audio.pause();audio.removeAttribute('src');audio.load();audio=null}}
function close(){if(closed)return;closed=true;app.classList.add('closing');cleanup();window.webview?.send('close',{})}
function onKey(e){if(e.key==='ArrowRight')show(index+1);else if(e.key==='ArrowLeft')show(index-1);else if(e.key==='Escape')close();else if(e.code==='Space'){e.preventDefault();togglePause()}}
function onStage(e){if(e.target.closest('button'))return;show(index+(e.clientX<innerWidth/2?-1:1))}
document.getElementById('close').addEventListener('click',close);mute.addEventListener('click',toggleMute);pause.addEventListener('click',togglePause);window.addEventListener('keydown',onKey);stage.addEventListener('click',onStage);window.addEventListener('pagehide',cleanup,{once:true});
const urls=[...new Set(S.heroArt.concat(S.watched.map(m=>m.cover),S.completed.map(m=>m.cover),S.recommendations.map(m=>m.cover)).filter(Boolean))];const preload=Promise.all(urls.map(url=>new Promise(resolve=>{const image=new Image();const timer=setTimeout(()=>{failedArt.add(url);image.src='';resolve()},6000);image.onload=()=>{clearTimeout(timer);resolve()};image.onerror=()=>{clearTimeout(timer);failedArt.add(url);resolve()};image.src=url})));preload.then(()=>{document.querySelectorAll('img').forEach(image=>{if(failedArt.has(image.src)||failedArt.has(image.getAttribute('src')))image.src=FALLBACK});loading.classList.add('hidden');show(0);setupAudio();raf=requestAnimationFrame(tick)});
})();
</script></body></html>`;
  }

  return { documentFor };
}

export type WrappedViewer = ReturnType<typeof createViewer>;
